"""Add status to HabitLog

Revision ID: c83c23c1f8ef
Revises: b080e04d643c
Create Date: 2025-08-12 12:49:22.830870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c83c23c1f8ef'
down_revision = 'b080e04d643c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habit_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habit_log', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
